$schema: https://raw.githubusercontent.com/remal-github-actions/sync-with-template/main/local-transformations.schema.json

repositories:
- remal-gradle-plugins/jacoco-to-cobertura

transformations:
- name: lombok.config-Java-11
  format: text
  includes:
  - lombok.config
  script: |
    return content + [
            '',
            '# Use `var` of Java 10 instead',
            'lombok.val.flagUsage = warning',
            '',
        ].join('\n')
